name: Docker Image Server CI - ghcr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: searxh/find-my-mines
          image_tag: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          context: "./Server"
          dockerfile: "./Server/Dockerfile"
